- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: Ensure Apache is running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
