# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
  
    config.vm.define "ubuntu-vm" do |vm|
      vm.vm.hostname = "ubuntu-vm"
      vm.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "4096"
        
        # From VirtualBox:
        # "Note Enabling the I/O APIC is required for 64-bit guest 
        # operating systems, especially Windows Vista; it is also 
        # required if you want to use more than one virtual CPU in 
        # a virtual machine."
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
      end
    end

end
  